# Generated by Django 2.1.3 on 2019-04-24 08:43

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('addr', models.CharField(max_length=128, unique=True, verbose_name='地址')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '代理',
                'verbose_name_plural': '代理',
            },
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('description', models.TextField(default='暂无', verbose_name='描述')),
                ('filename', models.CharField(max_length=256, verbose_name='文件名')),
                ('author', models.CharField(max_length=32, verbose_name='作者')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '爬虫',
                'verbose_name_plural': '爬虫',
            },
        ),
        migrations.CreateModel(
            name='SpiderEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='', verbose_name='事件信息')),
                ('level', models.IntegerField(choices=[(0, 'DEBUG'), (1, 'INFO'), (2, 'WARNING'), (3, 'ERROR'), (4, 'CRITICAL')], verbose_name='事件等级')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='更新时间')),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Spider', verbose_name='爬虫')),
            ],
            options={
                'verbose_name': '爬虫事件',
                'verbose_name_plural': '爬虫事件',
            },
        ),
    ]
