# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intelligence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('url', models.CharField(max_length=256, verbose_name='地址')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name_plural': '威胁情报',
                'verbose_name': '威胁情报',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类')),
            ],
        ),
        migrations.CreateModel(
            name='IntelligenceResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, verbose_name='地址')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('spider_type', models.IntegerField(verbose_name='爬虫类型')),
                ('last_refresh_time', models.DateTimeField(auto_now=True, verbose_name='上次刷新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='IntelligenceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类')),
            ],
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, verbose_name='昵称')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='intelligenceresource',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.ResourceCategory'),
        ),
        migrations.AddField(
            model_name='intelligence',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.IntelligenceCategory'),
        ),
        migrations.AddField(
            model_name='intelligence',
            name='tag',
            field=models.ManyToManyField(blank=True, to='reader.IntelligenceTag'),
        ),
    ]
