# Generated by Django 2.1.3 on 2019-04-24 08:43

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='认证名称')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '账号'), (1, 'Cookie'), (2, '请求头')], default=0, verbose_name='认证类型')),
                ('username', models.CharField(blank=True, default='', max_length=128, verbose_name='账号')),
                ('password', models.CharField(blank=True, default='', max_length=128, verbose_name='密码')),
                ('cookie', models.CharField(blank=True, default='', max_length=512, verbose_name='Cookie')),
                ('auth_header', models.CharField(blank=True, default='', max_length=128, verbose_name='认证请求头')),
                ('auth_value', models.CharField(blank=True, default='', max_length=128, verbose_name='认证Token')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '认证',
                'verbose_name_plural': '认证',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('link', models.URLField(max_length=512, verbose_name='链接')),
                ('description', models.TextField(default='暂无', verbose_name='描述')),
                ('author', models.CharField(default='Admin', max_length=64, verbose_name='作者')),
                ('refresh_gap', models.PositiveSmallIntegerField(default=60, verbose_name='刷新间隔')),
                ('refresh_status', models.PositiveSmallIntegerField(choices=[(0, 'NEVER'), (1, 'FAIL'), (2, 'RUNNING'), (3, 'SUCCESS')], verbose_name='刷新状态')),
                ('last_refresh_time', models.DateTimeField(verbose_name='上次刷新时间')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, '公开'), (1, '个人'), (2, '保密'), (3, '绝密')], verbose_name='等级')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否开启')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='更新时间')),
                ('auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.Authorization', verbose_name='认证')),
            ],
            options={
                'verbose_name': '订阅源',
                'verbose_name_plural': '订阅源',
            },
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名称')),
                ('description', models.TextField(default='暂无', verbose_name='描述')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订阅源分类',
                'verbose_name_plural': '订阅源分类',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.ResourceCategory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='resource',
            name='default_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.ArticleCategory', verbose_name='文章默认分类'),
        ),
        migrations.AddField(
            model_name='resource',
            name='default_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.ArticleTag', verbose_name='文章默认标签'),
        ),
        migrations.AddField(
            model_name='resource',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spider.Proxy', verbose_name='代理'),
        ),
        migrations.AddField(
            model_name='resource',
            name='spider_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spider.Spider', verbose_name='爬虫类型'),
        ),
    ]
