# Generated by Django 2.1.3 on 2019-04-30 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='is_deleted',
        ),
    ]
