# Generated by Django 2.1.3 on 2019-04-24 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('url', models.URLField(max_length=256, verbose_name='原始地址')),
                ('content', models.TextField(blank=True, verbose_name='文章内容')),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('hash', models.CharField(default='', max_length=512, verbose_name='文章哈希')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认分类')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='标签')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.ArticleCategory', verbose_name='分类'),
        ),
    ]
