# Generated by Django 2.1.3 on 2019-04-24 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.Resource', verbose_name='订阅源'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='article.ArticleTag', verbose_name='标签'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('title', 'hash')},
        ),
    ]
