# Generated by Django 2.1.3 on 2019-04-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190424_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hash',
            field=models.CharField(db_index=True, default='', max_length=512, verbose_name='文章哈希'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, max_length=256, verbose_name='标题'),
        ),
    ]
